// Nigerian Mathematics curriculum class selector.
// JSS1 is the currently loaded curriculum; the selector is structured for all levels.
(function(){
 const levels={Primary:Array.from({length:6},(_,i)=>`Primary ${i+1}`),JSS:['JSS 1','JSS 2','JSS 3'],SSS:['SSS 1','SSS 2','SSS 3']};
 const saved=(()=>{try{return JSON.parse(localStorage.getItem('mathbridge-class')||'null')}catch{return null}})()||{level:'JSS',className:'JSS 1'};
 const mount=()=>{if(document.getElementById('curriculum-picker'))return;const header=document.querySelector('header');if(!header)return;
 const box=document.createElement('section');box.id='curriculum-picker';box.innerHTML=`<div class="mb-picker-inner"><div class="mb-picker-title"><small>🇳🇬 NIGERIAN MATHEMATICS CURRICULUM</small><b>Choose your learning level and class</b></div><label>Level<select id="mb-level"><option value="Primary">Primary</option><option value="JSS">JSS</option><option value="SSS">SSS</option></select></label><label>Class<select id="mb-class"></select></label><button id="mb-apply">Use Class →</button></div><div id="mb-status"></div>`;
 const style=document.createElement('style');style.textContent='#curriculum-picker{padding:14px 20px;background:#fff;border-bottom:1px solid #e7edf5}.mb-picker-inner{max-width:1100px;margin:auto;display:flex;gap:12px;align-items:end;flex-wrap:wrap}.mb-picker-title{display:flex;flex-direction:column;gap:3px;margin-right:auto}.mb-picker-title small{font-size:11px;font-weight:800;color:#64748b}.mb-picker-title b{font-size:15px;color:#17213a}.mb-picker-inner label{font-size:11px;font-weight:800;color:#64748b;display:flex;flex-direction:column;gap:4px}.mb-picker-inner select{min-width:135px;padding:10px 12px;border:1px solid #d9e1ec;border-radius:10px;background:#fff;font-size:14px;color:#17213a}.mb-picker-inner button{border:0;border-radius:10px;padding:11px 15px;background:#2563eb;color:#fff;font-weight:800;cursor:pointer}.mb-picker-inner button:hover{filter:brightness(.96)}#mb-status{max-width:1100px;margin:7px auto 0;font-size:12px;font-weight:700}.available{color:#15803d}.coming{color:#b45309}@media(max-width:600px){.mb-picker-inner{align-items:stretch}.mb-picker-title{width:100%}.mb-picker-inner label,.mb-picker-inner select,.mb-picker-inner button{width:100%}}';document.head.appendChild(style);
 header.insertAdjacentElement('afterend',box);const level=box.querySelector('#mb-level'),cls=box.querySelector('#mb-class'),status=box.querySelector('#mb-status');level.value=saved.level;
 const fill=()=>{cls.innerHTML=levels[level.value].map(x=>`<option value="${x}">${x}</option>`).join('');cls.value=levels[level.value].includes(saved.className)?saved.className:levels[level.value][0]};fill();level.addEventListener('change',fill);
 box.querySelector('#mb-apply').onclick=()=>{const levelName=level.value,className=cls.value;localStorage.setItem('mathbridge-class',JSON.stringify({level:levelName,className}));if(className==='JSS 1'){status.textContent='JSS 1 Mathematics is currently available. Your existing JSS1 roadmap will be used.';status.className='available'}else{status.textContent=`${className} is selected. Its Nigerian Mathematics curriculum content will be added as that level is released.`;status.className='coming'}document.querySelector('.nav span')?.replaceChildren(document.createTextNode(`🇳🇬 ${className} • Nigerian Mathematics`));document.querySelector('.pill')?.replaceChildren(document.createTextNode(`🇳🇬 ${className} • Nigerian Mathematics`))};box.querySelector('#mb-apply').click();
 };
 new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});setTimeout(mount,100);setTimeout(mount,1000);
})();
