import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';import'./termStyles.css';
import{primary1Questions}from'./data/primary1Math';import{primary2Questions}from'./data/primary2Math';import{primary3Questions}from'./data/primary3Math';import{primary4Questions}from'./data/primary4Math';import{primary5Questions}from'./data/primary5Math';import{primary6Questions}from'./data/primary6Math';import{jss1Questions}from'./data/jss1Math';import{jss2Questions}from'./data/jss2Math';import{jss3Questions}from'./data/jss3Math';
import{primary1TermMap}from'./data/primary1TermMap';import{primary2TermMap}from'./data/primary2TermMap';import{primary3TermMap}from'./data/primary3TermMap';import{primary4TermMap}from'./data/primary4TermMap';import{primary5TermMap}from'./data/primary5TermMap';import{primary6TermMap}from'./data/primary6TermMap';import{jss1TermMap}from'./data/jss1TermMap';import{jss2TermMap}from'./data/jss2TermMap';import{jss3TermMap}from'./data/jss3TermMap';
import{PRIMARY1_LEARNING}from'./data/primary1LessonLearning';import{PRIMARY2_LEARNING}from'./data/primary2LessonLearning';import{PRIMARY3_LEARNING}from'./data/primary3LessonLearning';import{PRIMARY4_LEARNING}from'./data/primary4LessonLearning';import{PRIMARY5_LEARNING}from'./data/primary5LessonLearning';import{PRIMARY6_LEARNING}from'./data/primary6LessonLearning';import{JSS1_LEARNING}from'./data/jss1LessonLearning';import{JSS2_LEARNING}from'./data/jss2LessonLearning';import{JSS3_LEARNING}from'./data/jss3LessonLearning';
import{recordPrimary1TopicResult,getPrimary1ProgressSummary}from'./data/primary1Progress';import{recordPrimary2TopicResult,getPrimary2ProgressSummary}from'./data/primary2Progress';import{recordPrimary3TopicResult,getPrimary3ProgressSummary}from'./data/primary3Progress';import{recordPrimary4TopicResult,getPrimary4ProgressSummary}from'./data/primary4Progress';import{createPrimary6Progress,recordPrimary6TopicResult,getPrimary6ProgressSummary}from'./data/primary6Progress';import{createJSS1Progress,recordJSS1TopicResult,getJSS1ProgressSummary}from'./data/jss1Progress';import{createJSS2Progress,recordJSS2TopicResult,getJSS2ProgressSummary}from'./data/jss2Progress';import{createJSS3Progress,recordJSS3TopicResult,getJSS3ProgressSummary}from'./data/jss3Progress';
const CLASSES={Primary:['Primary 1','Primary 2','Primary 3','Primary 4','Primary 5','Primary 6'],JSS:['JSS 1','JSS 2','JSS 3']};
const MAPS={'Primary 1':primary1TermMap,'Primary 2':primary2TermMap,'Primary 3':primary3TermMap,'Primary 4':primary4TermMap,'Primary 5':primary5TermMap,'Primary 6':primary6TermMap,'JSS 1':jss1TermMap,'JSS 2':jss2TermMap,'JSS 3':jss3TermMap};
const QUESTIONS={'Primary 1':primary1Questions,'Primary 2':primary2Questions,'Primary 3':primary3Questions,'Primary 4':primary4Questions,'Primary 5':primary5Questions,'Primary 6':primary6Questions,'JSS 1':jss1Questions,'JSS 2':jss2Questions,'JSS 3':jss3Questions};
const LESSONS={'Primary 1':PRIMARY1_LEARNING,'Primary 2':PRIMARY2_LEARNING,'Primary 3':PRIMARY3_LEARNING,'Primary 4':PRIMARY4_LEARNING,'Primary 5':PRIMARY5_LEARNING,'Primary 6':PRIMARY6_LEARNING,'JSS 1':JSS1_LEARNING,'JSS 2':JSS2_LEARNING,'JSS 3':JSS3_LEARNING};
const BLANK={"Primary 1":()=>({className:'Primary 1',masteredTopics:[],topicResults:{}}),"Primary 2":()=>({className:'Primary 2',masteredTopics:[],topicResults:{}}),"Primary 3":()=>({className:'Primary 3',masteredTopics:[],topicResults:{}}),"Primary 4":()=>({className:'Primary 4',masteredTopics:[],topicResults:{}}),"Primary 5":()=>({className:'Primary 5',masteredTopics:[],topicResults:{}}),"Primary 6":createPrimary6Progress,"JSS 1":createJSS1Progress,"JSS 2":createJSS2Progress,"JSS 3":createJSS3Progress};
const SUMMARY={"Primary 1":getPrimary1ProgressSummary,"Primary 2":getPrimary2ProgressSummary,"Primary 3":getPrimary3ProgressSummary,"Primary 4":getPrimary4ProgressSummary,"Primary 5":getPrimary5ProgressSummary,"Primary 6":getPrimary6ProgressSummary,"JSS 1":getJSS1ProgressSummary,"JSS 2":getJSS2ProgressSummary,"JSS 3":getJSS3ProgressSummary};
const RECORD={"Primary 1":recordPrimary1TopicResult,"Primary 2":recordPrimary2TopicResult,"Primary 3":recordPrimary3TopicResult,"Primary 4":recordPrimary4TopicResult,"Primary 5":recordPrimary5TopicResult,"Primary 6":recordPrimary6TopicResult,"JSS 1":recordJSS1TopicResult,"JSS 2":recordJSS2TopicResult,"JSS 3":recordJSS3TopicResult};
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const key=c=>`mb-${c.toLowerCase().replaceAll(' ','')}-progress`;
function initialProgress(){const out={};Object.keys(MAPS).forEach(c=>{try{out[c]=JSON.parse(localStorage.getItem(key(c))||'null')||BLANK[c]()}catch{out[c]=BLANK[c]()}});return out}
function App(){
 const[level,setLevel]=useState('Primary'),[className,setClassName]=useState('Primary 1'),[term,setTerm]=useState('Term 1'),[screen,setScreen]=useState('home'),[topic,setTopic]=useState(null),[questions,setQuestions]=useState([]),[index,setIndex]=useState(0),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[practice,setPractice]=useState(false),[progress,setProgress]=useState(initialProgress),[feedback,setFeedback]=useState(false),[student,setStudent]=useState('');
 const map=MAPS[className]||{},terms=Object.keys(map),topics=map[term]?.topics||[],p=progress[className]||BLANK[className](),summary=SUMMARY[className](p,topics),termIndex=terms.indexOf(term);
 const previousTerm=termIndex>0?terms[termIndex-1]:null;
 const previousComplete=previousTerm?SUMMARY[className](p,map[previousTerm]?.topics||[]).complete:true;
 const lockedTerm=idx=>idx>0&&!SUMMARY[className](p,map[terms[idx-1]]?.topics||[]).complete;
 const poolForTopic=useMemo(()=>topic?(QUESTIONS[className]||[]).filter(q=>q.topic===topic):[],[className,topic]);
 const save=(next)=>{setProgress(x=>({...x,[className]:next}));localStorage.setItem(key(className),JSON.stringify(next))};
 const chooseClass=e=>{const c=e.target.value;setClassName(c);setTerm('Term 1');setTopic(null);setScreen('home')};
 const startAssessment=()=>{const pool=(QUESTIONS[className]||[]).filter(q=>topics.includes(q.topic));if(!pool.length){setScreen('protected');return}setQuestions(shuffle(pool).slice(0,Math.min(10,pool.length)));setIndex(0);setSelected(null);setScore(0);setPractice(false);setFeedback(false);setScreen('quiz')};
 const startPractice=()=>{if(!topic)return;const pool=shuffle(poolForTopic).slice(0,Math.min(5,poolForTopic.length));if(!pool.length)return;setQuestions(pool);setIndex(0);setSelected(null);setScore(0);setPractice(true);setFeedback(false);setScreen('quiz')};
 const answer=n=>{if(selected!==null)return;setSelected(n);setFeedback(true)};
 const next=()=>{if(selected===null)return;const correct=selected===questions[index].answer;const nextScore=score+(correct?1:0);if(index<questions.length-1){setScore(nextScore);setIndex(index+1);setSelected(null);setFeedback(false);return}setScore(nextScore);if(practice&&topic){const nextProgress=RECORD[className](p,topic,nextScore,questions.length);save(nextProgress)}setScreen('result')};
 const beginTopic=t=>{setTopic(t);setScreen('lesson')};
 const continueTerm=()=>{if(termIndex<terms.length-1){setTerm(terms[termIndex+1]);setTopic(null);setScreen('home')}};
 const classOrder=[...CLASSES.Primary,...CLASSES.JSS],classIdx=classOrder.indexOf(className),nextClass=classIdx<classOrder.length-1?classOrder[classIdx+1]:null;
 const goNextClass=()=>{if(!nextClass)return;setClassName(nextClass);setLevel(nextClass.startsWith('Primary')?'Primary':'JSS');setTerm('Term 1');setTopic(null);setScreen('home')};
 const nextTerm=termIndex<terms.length-1?terms[termIndex+1]:null;
 const completion=summary.complete;
 return <div className="app"><header><button className="logo" onClick={()=>setScreen('home')}>Math<span>Bridge</span></button><span>🇳🇬 Nigerian Mathematics</span></header>
 {screen==='home'&&<main className="hero"><section className="curriculum-selector"><b>Nigerian Mathematics Curriculum</b><small>Learn in order: Term 1 → Term 2 → Term 3</small><div className="selector-grid"><label>Level<select value={level} onChange={e=>{setLevel(e.target.value);setClassName(CLASSES[e.target.value][0]);setTerm('Term 1');setScreen('home')}}>{Object.keys(CLASSES).map(x=><option key={x}>{x}</option>)}</select></label><label>Class<select value={className} onChange={chooseClass}>{CLASSES[level].map(x=><option key={x}>{x}</option>)}</select></label><label>Term<select value={term} onChange={e=>{const idx=terms.indexOf(e.target.value);if(idx>=0&&!lockedTerm(idx))setTerm(e.target.value)}}>{terms.map((t,idx)=><option key={t} value={t} disabled={lockedTerm(idx)}>{lockedTerm(idx)?`🔒 ${t}`:t}</option>)}</select></label></div><button className="primary" onClick={startAssessment}>Start {className} • {term} →</button><p>Selected: <b>{level} • {className} • {term}</b></p><p className="note">Different questions are selected each time you start.</p></section>
 <section className="report"><div className="term-banner"><span>📈 {className}</span><b>{term}</b><small>{summary.masteredCount}/{summary.totalTopics} topics mastered</small></div><div className="progress"><span style={{width:`${summary.percentage}%`}}/></div><p><b>{summary.percentage}% complete</b> — mastery target is 80%.</p>{topics.map(t=>{const mastered=(p.masteredTopics||[]).includes(t);return <button className="secondary" key={t} onClick={()=>beginTopic(t)}>📘 {t} {mastered?'✓':''}</button>})}{completion&&<button className="primary" onClick={()=>setScreen('certificate')}>🏆 {nextTerm?'Term completed':'Class completed'} →</button>}</section>
 <div className="pill">🇳🇬 {className} • {term}</div><h1>Learn Maths.<br/><span>Make it easy.</span></h1><p>Short lessons. Randomised practice. Master each term before moving forward.</p><div className="cards"><div><b>🧠 Assess</b><small>Fresh questions from the selected term.</small></div><div><b>💡 Learn</b><small>Simple explanations and worked examples.</small></div><div><b>🏆 Master</b><small>Reach 80% before the next stage unlocks.</small></div></div></main>}
 {screen==='lesson'&&<main className="result"><div className="pill">📘 {className} • {term}</div><p className="step">LESSON • {topic}</p><h2>{LESSONS[className]?.[topic]?.title||topic}</h2><div className="report"><p><b>Learn:</b> {LESSONS[className]?.[topic]?.teach||'Study the key idea carefully.'}</p><p><b>Example:</b> {LESSONS[className]?.[topic]?.example||'Work through an example step by step.'}</p><p><b>Tip:</b> {LESSONS[className]?.[topic]?.tip||'Write each step clearly and check your answer.'}</p><p><b>Question bank:</b> {poolForTopic.length} questions.</p></div><button className="primary" onClick={startPractice} disabled={!poolForTopic.length}>Start Random Practice →</button><button className="secondary" onClick={()=>setScreen('home')}>Back to curriculum</button></main>}
 {screen==='quiz'&&questions.length>0&&<main className="quiz"><div className="term-banner"><span>📘 {className}</span><b>{term}</b><small>{practice?'Practice':'Assessment'}</small></div><div className="progress"><span style={{width:`${(index+1)/questions.length*100}%`}}/></div><p className="step">QUESTION {index+1} OF {questions.length}</p><div className="topic-label">Topic: {questions[index].topic}</div><h2>{questions[index].q}</h2><div className="answers">{questions[index].options.map((x,n)=><button key={`${questions[index].id||index}-${n}`} className={selected===n?'selected-answer':''} onClick={()=>answer(n)} disabled={selected!==null}>{x}<span>{selected===n?'✓':'→'}</span></button>)}</div>{feedback&&<div className="report feedback"><h3>{selected===questions[index].answer?'✅ Correct!':'💡 Not quite.'}</h3>{questions[index].explanation&&<p>{questions[index].explanation}</p>}<p><b>Correct answer:</b> {questions[index].options[questions[index].answer]}</p></div>}<button className="primary" onClick={next} disabled={selected===null}>{index===questions.length-1?'Finish →':'Next →'}</button><p className="encourage">Your answer is highlighted immediately. You can see the correct answer before continuing.</p></main>}
 {screen==='result'&&<main className="result"><div className="badge">{score>=questions.length*.8?'🏆':'📊'}</div><p className="step">{practice?'MASTERY PRACTICE RESULT':'TERM ASSESSMENT RESULT'}</p><h2>{score>=questions.length*.8?'Great work!':'Keep practising.'}</h2><div className="score"><strong>{questions.length?Math.round(score/questions.length*100):0}%</strong><span>{score} of {questions.length} correct</span></div><div className="report"><p>{practice?(score>=questions.length*.8?'This topic is now mastered and your progress has been saved.':'You need 80% to master this topic. Review the lesson and try a new random set.'):'Assessment complete. Choose a topic above to learn and practise it.'}</p></div><button className="primary" onClick={()=>setScreen('home')}>Back to {term} Curriculum →</button>{practice&&<button className="secondary" onClick={startPractice}>New Random Set</button>}</main>}
 {screen==='certificate'&&<main className="result"><div className="badge">🏆</div><p className="step">{nextTerm?'TERM COMPLETION':'CLASS COMPLETION'}</p><h2>{nextTerm?`${className} ${term} completed`:`${className} Mathematics completed`}</h2><div className="report"><p>You reached the required 80% mastery level across all topics in {term}.</p><p><b>Next stage:</b> {nextTerm?`${className} ${nextTerm}`:(nextClass||'Curriculum complete')}</p></div>{nextTerm?<button className="primary" onClick={continueTerm}>Continue to {nextTerm} →</button>:nextClass&&<button className="primary" onClick={goNextClass}>Continue to {nextClass} →</button>}<button className="secondary" onClick={()=>setScreen('home')}>Back to curriculum</button></main>}
 {screen==='protected'&&<main className="result"><div className="badge">🔒</div><h2>{className} • {term} is being prepared</h2><div className="report"><p>There are not enough questions for this term yet. We will not pretend the stage is complete.</p></div><button className="primary" onClick={()=>setScreen('home')}>Back to curriculum →</button></main>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);