import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import {curriculum,curriculumSource,levelOptions} from './data/curriculum';
import {jss1Math,jss1Questions} from './data/jss1Math';

function App(){
 const [screen,setScreen]=useState('home');
 const [i,setI]=useState(0);
 const [answers,setAnswers]=useState({});
 const [name,setName]=useState('');
 const [level,setLevel]=useState('JSS1');
 const [lessonTopic,setLessonTopic]=useState('Fractions');
 const [mastery,setMastery]=useState(0);
 const selectedLevel=levelOptions.find(x=>x.value===level);
 const levelTopics=curriculum.jss.levels[level]?.topics||curriculum.primary.levels[level]?.topics||curriculum.sss.levels[level]?.topics||[];
 const questions=level==='JSS1'?jss1Questions:[];
 const diagnosticQuestions=useMemo(()=>{
   const seen=new Set();
   return questions.filter(q=>{if(seen.has(q.topic))return false;seen.add(q.topic);return true;});
 },[questions]);
 const topicResults=useMemo(()=>jss1Math.strands.flatMap(s=>s.topics).map(topic=>{
   const qs=questions.filter(q=>q.topic===topic);
   const answered=qs.filter(q=>answers[q.id]!==undefined);
   const correct=answered.filter(q=>answers[q.id]===q.answer).length;
   return {topic,answered:answered.length,total:qs.length,score:answered.length?Math.round(correct/answered.length*100):0};
 }),[answers,questions]);
 const overall=useMemo(()=>{const answered=Object.keys(answers).length;const correct=questions.filter(q=>answers[q.id]===q.answer).length;return answered?Math.round(correct/answered*100):0},[answers,questions]);
 const weak=topicResults.filter(x=>x.answered&&x.score<70).sort((a,b)=>a.score-b.score).slice(0,3);
 const start=()=>{setI(0);setAnswers({});setScreen('quiz')};
 const answer=(n)=>{const q=diagnosticQuestions[i];const next={...answers,[q.id]:n};setAnswers(next);if(i<diagnosticQuestions.length-1)setI(i+1);else{const firstWeak=jss1Math.strands.flatMap(s=>s.topics).map(t=>{const r=next[diagnosticQuestions.find(q=>q.topic===t)?.id];return r===undefined?null:t}).find(Boolean);setLessonTopic(firstWeak||diagnosticQuestions[0]?.topic||levelTopics[0]||'Foundation Builder');setScreen('result')}};
 const topicQuestion=questions.find(q=>q.topic===lessonTopic)||questions[0];
 return <div className="app"><header><button className="logo" onClick={()=>setScreen('home')}>Math<span>Bridge</span></button><div className="nav"><span>🇳🇬 NERDC-aligned</span><button className="ghost" onClick={()=>setScreen('home')}>Home</button></div></header>
 {screen==='home'&&<main className="hero"><div className="pill">🇳🇬 Nigerian Curriculum Mathematics</div><h1>Learn Maths.<br/><span>Lose the Fear.</span></h1><p>MathBridge diagnoses your JSS1 foundation, identifies weak topics, and creates a simple learning path around what you actually need.</p><div className="cards"><div><b>🧠 Diagnose</b><small>One diagnostic question per JSS1 topic.</small></div><div><b>💡 Simplify</b><small>Learn easy methods, formulas and memory tricks.</small></div><div><b>🏆 Improve</b><small>Practise, master topics and earn rewards.</small></div></div><div className="namebox"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your first name (optional)"/><select value={level} onChange={e=>setLevel(e.target.value)}>{levelOptions.map(x=><option key={x.value} value={x.value}>{x.group} — {x.label}</option>)}</select><button className="primary" onClick={start}>Start My Maths Health Check →</button></div><div className="curriculum-card"><b>{selectedLevel?.label} curriculum map</b><p>{levelTopics.slice(0,8).join(' • ')}</p>{level==='JSS1'&&<small>JSS1 is the first fully mapped curriculum in this MVP: {diagnosticQuestions.length} diagnostic topics and a growing verified-answer question bank.</small>}</div><p className="curriculum-note">Curriculum basis: NERDC. <a href={curriculumSource.basicUrl} target="_blank" rel="noreferrer">Official curriculum portal</a> · <a href={curriculumSource.jssMathUrl} target="_blank" rel="noreferrer">JSS Mathematics document</a></p><p className="note">Free • One question per topic • No pressure</p></main>}
 {screen==='quiz'&&<main className="quiz"><div className="progress"><span style={{width:`${((i+1)/diagnosticQuestions.length)*100}%`}}/></div><p className="step">{selectedLevel?.label?.toUpperCase()} • DIAGNOSTIC {i+1} OF {diagnosticQuestions.length}</p><div className="topic-label">{diagnosticQuestions[i].topic}</div><h2>{diagnosticQuestions[i].q}</h2><div className="answers">{diagnosticQuestions[i].options.map((x,n)=><button key={x} onClick={()=>answer(n)}>{x}<span>→</span></button>)}</div><p className="encourage">💙 No judgment. Your answers help us find the right starting point.</p></main>}
 {screen==='result'&&<main className="result"><div className="badge">🎯</div><p className="step">YOUR MATHEMATICS HEALTH REPORT</p><h2>{name?`${name}, here is your JSS1 report.`:'Here is your JSS1 report.'}</h2><div className="levelpill">🇳🇬 JSS 1 • NERDC-aligned diagnostic</div><div className="score"><strong>{overall}%</strong><span>overall diagnostic</span></div><div className="report"><h3>Your topic map</h3><div className="topic-results">{topicResults.filter(x=>x.answered).map(x=><div key={x.topic}><span>{x.topic}</span><b className={x.score<70?'weakscore':''}>{x.score}%</b></div>)}</div><h3>Priority gaps</h3>{weak.length?<div className="tags">{weak.map(x=><span key={x.topic}>🔴 {x.topic} • {x.score}%</span>)}</div>:<div className="tags"><span>🟢 No major gap detected in assessed topics</span></div>}<div className="recommend">📚 <span>Recommended starting point</span><b>{weak[0]?.topic||diagnosticQuestions[0]?.topic||'Foundation Builder'}</b><small>MathBridge will teach the concept simply, then give you guided practice and a mastery challenge.</small></div></div><button className="primary" onClick={()=>setScreen('lesson')}>Start My Personalized Learning Path →</button></main>}
 {screen==='lesson'&&<main className="lesson"><div className="pill">✨ Personalized lesson</div><p className="step">JSS1 • {lessonTopic}</p><h2>{lessonTopic} made simple</h2><p className="lead">We start with one clear idea, one easy method, then practise until the concept becomes natural.</p><div className="formula"><small>THE EASY METHOD</small><strong>{lessonTopic==='Fractions'?'Find an equivalent fraction before combining different denominators.':topicQuestion.explanation}</strong><p>{lessonTopic==='Fractions'?'½ + ¼ → 2/4 + 1/4 → 3/4':'Read → choose the method → calculate → check your answer.'}</p></div><div className="song">🎵 <b>Memory Song</b><br/>“Small steps, clear mind, maths gets easier every time!”</div><div className="lessonsteps"><span>1 Learn</span><span>2 Example</span><span>3 Practise</span><span>4 Master</span></div><button className="primary" onClick={()=>setScreen('practice')}>Practise This Skill →</button></main>}
 {screen==='practice'&&<main className="challenge"><div className="pill">✏️ Guided Practice</div><h2>Let's build confidence.</h2><p>Here is a verified-answer example from the JSS1 question bank for <b>{lessonTopic}</b>.</p><div className="practicecards"><div><b>{topicQuestion.q}</b><small>Method: {topicQuestion.explanation}</small><span>Answer: {topicQuestion.options[topicQuestion.answer]}</span></div></div><button className="primary" onClick={()=>setScreen('challenge')}>Take Mastery Challenge →</button></main>}
 {screen==='challenge'&&<main className="challenge"><div className="pill">⏱️ Mastery Challenge</div><h2>Ready to prove it?</h2><p>Your mastery target is <b>80%</b>. Students who reach the target can qualify for the MathBridge reward pathway.</p><div className="challengebox"><span>🏆</span><b>{lessonTopic} Mastery</b><small>Attempt 1 of 2</small><div className="challengeScore">{mastery}%</div></div><button className="primary" onClick={()=>{setMastery(90);setScreen('dashboard')}}>Submit Challenge</button></main>}
 {screen==='dashboard'&&<main className="dashboard"><div className="dashhead"><div><p className="step">YOUR LEARNING DASHBOARD</p><h2>{name?`Welcome back, ${name}!`:'Welcome back!'}</h2><p className="leveltext">JSS1 • Nigerian curriculum pathway</p></div><div className="streak">🔥 1 day streak</div></div><div className="stats"><div><small>Diagnostic</small><b>{overall}%</b></div><div><small>Mastery</small><b>{mastery}%</b></div><div><small>Points</small><b>120</b></div></div><div className="report"><h3>🏆 Badge earned</h3><p><b>{lessonTopic} Starter</b> — You completed your first learning cycle.</p><div className="reward">🎁 Master the full curriculum to qualify for free access to the next level.</div></div><button className="primary" onClick={()=>setScreen('home')}>Continue Learning</button></main>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);
