import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';import'./termStyles.css';
import{primary1Questions}from'./data/primary1Math';import{primary1Lessons}from'./data/primary1Lessons';
const CURRICULUM={Primary:['Primary 1','Primary 2','Primary 3','Primary 4','Primary 5','Primary 6'],JSS:['JSS 1','JSS 2','JSS 3'],SSS:['SSS 1','SSS 2','SSS 3']};
const LEVELS=Object.keys(CURRICULUM),P1='Primary 1';
const TERMS={'Term 1':['Whole numbers 1-5','Whole number 0 (Zero)','Whole numbers 6-9','Whole number 10','Whole numbers 1-99','Fractions: halves and quarters','Addition'],'Term 2':['Subtraction','Open sentences','Nigerian money','Length','Time'],'Term 3':['Weight','2-dimensional shapes','3-dimensional shapes','Data collection']};
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[j],x[i]]=[x[i],x[j]]}return x};
const unique=a=>[...new Set(a)];
function App(){
 const[level,setLevel]=useState('Primary'),[className,setClassName]=useState(P1),[term,setTerm]=useState('Term 1'),[screen,setScreen]=useState('home'),[name,setName]=useState(''),[topic,setTopic]=useState(''),[quiz,setQuiz]=useState([]),[qi,setQi]=useState(0),[answers,setAnswers]=useState({}),[practice,setPractice]=useState([]),[pi,setPi]=useState(0),[pAnswer,setPAnswer]=useState(null),[test,setTest]=useState([]),[ti,setTi]=useState(0),[tAnswers,setTAnswers]=useState([]),[attempt,setAttempt]=useState(1),[score,setScore]=useState(null),[mastered,setMastered]=useState(()=>{try{return JSON.parse(localStorage.getItem('mb-p1-mastered')||'[]')}catch{return[]}}),[weakHistory,setWeakHistory]=useState(()=>{try{return JSON.parse(localStorage.getItem('mb-p1-weak')||'{}')}catch{return{}}});
 const classReady=className===P1,topics=TERMS[term],bank=primary1Questions,topicBank=t=>bank.filter(q=>q.topic===t),done=topics.filter(t=>mastered.includes(t)),termComplete=topics.length>0&&done.length===topics.length;
 const diagnostic=useMemo(()=>shuffle(bank).slice(0,Math.min(10,bank.length)),[screen]);
 const start=()=>{if(!classReady){setScreen('notReady');return}setAnswers({});setQi(0);setScreen('diagnostic')};
 const choose=n=>setAnswers(a=>({...a,[diagnostic[qi].id]:n}));
 const finishDiagnostic=()=>{const scores={};diagnostic.forEach(q=>{scores[q.topic]??={c:0,n:0};scores[q.topic].n++;if(answers[q.id]===q.answer)scores[q.topic].c++});const weakest=Object.entries(scores).sort((a,b)=>(a[1].c/a[1].n)-(b[1].c/b[1].n))[0]?.[0]||topics.find(t=>!mastered.includes(t))||topics[0];setTopic(weakest);setScreen('result')};
 const startPractice=()=>{const pool=shuffle(topicBank(topic));setPractice(pool.slice(0,Math.min(5,pool.length)));setPi(0);setPAnswer(null);setScreen('practice')};
 const startTest=()=>{let pool=shuffle(topicBank(topic));if(pool.length<3)pool=shuffle([...pool,...bank.filter(q=>q.topic!==topic)]);setTest(pool.slice(0,Math.min(5,pool.length)));setTi(0);setTAnswers([]);setAttempt(1);setScore(null);setScreen('mastery')};
 const nextPractice=()=>{if(pAnswer===null)return;if(pi<practice.length-1){setPi(pi+1);setPAnswer(null)}else startTest()};
 const submitTest=n=>{const next=[...tAnswers,n];setTAnswers(next);if(ti<test.length-1){setTi(ti+1);return}const correct=test.reduce((s,q,i)=>s+(next[i]===q.answer?1:0),0),result=Math.round(correct/test.length*100),nextWeak={...weakHistory,[topic]:result};setScore(result);setWeakHistory(nextWeak);try{localStorage.setItem('mb-p1-weak',JSON.stringify(nextWeak))}catch{}if(result>=80){const m=unique([...mastered,topic]);setMastered(m);try{localStorage.setItem('mb-p1-mastered',JSON.stringify(m))}catch{}}};
 const retry=()=>{if(attempt>=2)return;let pool=shuffle(topicBank(topic));if(pool.length<3)pool=shuffle([...pool,...bank.filter(q=>q.topic!==topic)]);setTest(pool.slice(0,Math.min(5,pool.length)));setTi(0);setTAnswers([]);setAttempt(2);setScore(null)};
 const nextTopic=topics.find(t=>!mastered.includes(t)&&t!==topic)||topics.find(t=>!mastered.includes(t));
 const goNext=()=>{if(termComplete){setScreen('termComplete');return}if(nextTopic){setTopic(nextTopic);setScreen('lesson')}else setScreen('home')};
 const selectLevel=e=>{const l=e.target.value;setLevel(l);setClassName(CURRICULUM[l][0]);setScreen('home')};
 return <div className="app"><header><button className="logo" onClick={()=>setScreen('home')}>Math<span>Bridge</span></button><div className="nav"><span>🇳🇬 Nigerian Mathematics</span><button className="ghost" onClick={()=>setScreen('progress')}>My Progress</button></div></header>
 {screen==='home'&&<main className="hero"><section className="curriculum-selector"><div className="selector-heading"><span>🇳🇬</span><div><b>Nigerian Mathematics Curriculum</b><small>Choose your level, class and term</small></div></div><div className="selector-grid"><label>Level<select value={level} onChange={selectLevel}>{LEVELS.map(x=><option key={x}>{x}</option>)}</select></label><label>Class<select value={className} onChange={e=>{setClassName(e.target.value);setScreen('home')}}>{CURRICULUM[level].map(x=><option key={x}>{x}</option>)}</select></label><label>Term<select value={term} onChange={e=>setTerm(e.target.value)}>{Object.keys(TERMS).map(x=><option key={x}>{x}</option>)}</select></label></div><button className="primary" onClick={start}>Start {className} →</button><small className="curriculum-status">Selected pathway: <b>{level} • {className} • {term}</b></small></section><div className="pill">🇳🇬 {className} • Nigerian Mathematics</div><h1>Learn Maths.<br/><span>Make it easy.</span></h1><p>MathBridge diagnoses gaps, explains maths simply, gives fresh practice and helps learners master each topic before moving forward.</p><div className="cards"><div><b>🧠 Diagnose</b><small>Find areas that need attention.</small></div><div><b>💡 Learn</b><small>Simple steps, examples and memory aids.</small></div><div><b>🏆 Master</b><small>Practise and pass a mastery challenge.</small></div></div><div className="namebox"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your first name (optional)"/><button className="primary" onClick={start}>Start My Maths Check →</button></div><div className="curriculum-card"><b>{className} • {term}</b><p>{topics.join(' • ')}</p>{classReady&&<small>Primary 1 is the active curriculum being completed first. Other classes are protected until their verified content is loaded.</small>}</div></main>}
 {screen==='notReady'&&<main className="result"><div className="badge">🇳🇬</div><p className="step">CURRICULUM PROTECTION</p><h2>{className} is selected</h2><div className="report"><h3>No substitute questions</h3><p>MathBridge will not give a learner Primary 1 questions under another class. {className} becomes available after its own Nigerian Mathematics curriculum, lessons and question bank are verified and connected.</p></div><button className="primary" onClick={()=>{setClassName(P1);setLevel('Primary');setScreen('home')}}>Use Primary 1 →</button></main>}
 {screen==='diagnostic'&&<main className="quiz"><div className="term-banner"><span>📘 {className}</span><b>{term}</b><small>Diagnostic</small></div><div className="progress"><span style={{width:`${(qi+1)/diagnostic.length*100}%`}}/></div><p className="step">{term.toUpperCase()} • QUESTION {qi+1} OF {diagnostic.length}</p><div className="topic-label">Topic: {diagnostic[qi]?.topic}</div><h2>{diagnostic[qi]?.q}</h2><div className="answers">{diagnostic[qi]?.options.map((x,n)=><button className={answers[diagnostic[qi].id]===n?'selected-answer':''} key={`${x}-${n}`} onClick={()=>choose(n)}>{x}<span>{answers[diagnostic[qi].id]===n?'✓':'→'}</span></button>)}</div><div className="question-nav"><button className="secondary" disabled={qi===0} onClick={()=>setQi(qi-1)}>← Back</button><button className="primary" disabled={answers[diagnostic[qi]?.id]===undefined} onClick={()=>qi<diagnostic.length-1?setQi(qi+1):finishDiagnostic()}>{qi===diagnostic.length-1?'Finish Check':'Next →'}</button></div><p className="encourage">💙 Your selected answer is highlighted.</p></main>}
 {screen==='result'&&<main className="result"><div className="badge">🎯</div><p className="step">DIAGNOSIS</p><h2>{name?`${name}, we found your next step.`:'We found your next step.'}</h2><div className="report"><h3>Priority learning area</h3><div className="recommend"><span>📚 {term}</span><b>{topic}</b><small>MathBridge will teach this topic simply before testing mastery.</small></div></div><button className="primary" onClick={()=>setScreen('lesson')}>Show Me How →</button></main>}
 {screen==='lesson'&&<main className="lesson"><div className="term-banner"><span>📘 {className}</span><b>{term}</b><small>{topic}</small></div><p className="step">LEARN • {topic.toUpperCase()}</p><h2>Let's make {topic} easy.</h2><div className="report"><h3>💡 Simple explanation</h3><p>{primary1Lessons[topic]?.simple||'Learn the idea step by step.'}</p><h3>🪜 Easy method</h3><p>{primary1Lessons[topic]?.method||'Break the problem into small steps and check your work.'}</p><h3>🧠 Remember it</h3><p>{primary1Lessons[topic]?.memory||'Small steps make maths easier.'}</p><div className="recommend"><span>Worked example</span><b>{primary1Lessons[topic]?.example||'Try a simple example and explain each step.'}</b></div></div><div className="lessonsteps"><span>1 Learn ✓</span><span>2 Practise</span><span>3 Master</span></div><button className="primary" onClick={startPractice}>Start Practice →</button></main>}
 {screen==='practice'&&<main className="challenge"><div className="term-banner"><span>📘 {className}</span><b>{term}</b><small>{topic}</small></div><p className="step">PRACTICE {pi+1} OF {practice.length}</p><h2>{practice[pi]?.q}</h2><div className="answers">{practice[pi]?.options.map((x,n)=><button className={pAnswer===n?'selected-answer':''} key={`${x}-${n}`} onClick={()=>setPAnswer(n)}>{x}<span>{pAnswer===n?'✓':'→'}</span></button>)}</div>{pAnswer!==null&&<div className="report feedback"><h3>{pAnswer===practice[pi].answer?'✅ Correct!':'💡 Learn from the mistake'}</h3><p>{practice[pi].explanation}</p><p><b>Correct answer:</b> {practice[pi].options[practice[pi].answer]}</p></div>}<button className="primary" disabled={pAnswer===null} onClick={nextPractice}>{pi===practice.length-1?'Take Timed Mastery →':'Next Practice →'}</button></main>}
 {screen==='mastery'&&<main className="challenge"><div className="term-banner"><span>📘 {className}</span><b>{term}</b><small>{topic} • Timed Mastery</small></div>{score===null?<><p className="step">ATTEMPT {attempt} OF 2 • TARGET 80%</p><h2>{test[ti]?.q}</h2><div className="answers">{test[ti]?.options.map((x,n)=><button key={`${x}-${n}`} onClick={()=>submitTest(n)}>{x}<span>→</span></button>)}</div><p className="encourage">⏱️ Choose carefully. You have only two mastery attempts.</p></>:<><div className="badge">{score>=80?'🏆':'💪'}</div><p className="step">MASTERY RESULT</p><h2>{score>=80?'Topic mastered!':'Keep learning and try again.'}</h2><div className="score"><strong>{score}%</strong><span>mastery score</span></div><div className="report">{score>=80?<><h3>🎁 Reward unlocked</h3><p>You mastered <b>{topic}</b>. You can move forward to the next learning unit.</p></>:<><h3>🔎 Weak point recorded</h3><p><b>{topic}</b> needs more practice. {attempt<2?'You have one mastery attempt remaining.':'Both mastery attempts have been used. Continue with the remedial lesson before progressing.'}</p></>}</div>{score>=80?<button className="primary" onClick={goNext}>{termComplete?'View Term Report':'Next Learning Unit →'}</button>:attempt<2?<button className="primary" onClick={retry}>Try Mastery Again →</button>:<button className="primary" onClick={()=>setScreen('lesson')}>Review {topic} →</button>}</>}</main>}
 {screen==='termComplete'&&<main className="result"><div className="badge">🏆</div><p className="step">TERM COMPLETE</p><h2>{name?`Well done, ${name}!`:'Well done!'}</h2><div className="report"><h3>{className} • {term}</h3><p>You have mastered every mapped Primary 1 topic in this term.</p><div className="tags">{topics.map(t=><span key={t}>✓ {t}</span>)}</div><h3>🔎 Areas for further help</h3>{Object.entries(weakHistory).filter(([t])=>topics.includes(t)).length?<div className="tags">{Object.entries(weakHistory).filter(([t])=>topics.includes(t)).sort((a,b)=>a[1]-b[1]).map(([t,s])=><span key={t}>📌 {t} • {s}%</span>)}</div>:<p>No mastery scores have been recorded yet.</p>}</div><button className="primary" onClick={()=>setScreen('progress')}>View My Progress →</button></main>}
 {screen==='progress'&&<main className="result"><div className="badge">📊</div><p className="step">MY PROGRESS</p><h2>{className} • {term}</h2><div className="report"><h3>Mastery</h3><p>{done.length} of {topics.length} topics mastered in this term.</p><div className="progress"><span style={{width:`${done.length/topics.length*100}%`}}/></div><div className="tags">{topics.map(t=><span key={t}>{mastered.includes(t)?'🏆':'🔒'} {t}</span>)}</div><h3>Weak points</h3>{Object.entries(weakHistory).length?<div className="tags">{Object.entries(weakHistory).sort((a,b)=>a[1]-b[1]).slice(0,5).map(([t,s])=><span key={t}>🔴 {t} • {s}%</span>)}</div>:<p>Complete a mastery test to identify weak points.</p>}</div><button className="primary" onClick={()=>setScreen('home')}>← Back to Home</button></main>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);
