import{getQuestionsForLevel}from'./data/questionBank';
import{supabase,supabaseConfigured}from'./supabaseClient';
const fail=message=>({ok:false,error:new Error(message)});const cloud=()=>supabaseConfigured&&supabase;
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const publicQuestion=q=>({id:q.id,q:q.q,options:q.options,topic:q.topic,difficulty:q.difficulty,explanation:q.explanation,objective:q.objective,classLevel:q.classLevel,term:q.term,week:q.week,sourceType:q.sourceType});
export const getSchoolTests=async schoolId=>{if(!cloud()||!schoolId)return{data:[],error:null};const{data,error}=await supabase.from('school_tests').select('*,school_classes(class_name,class_level)').eq('school_id',schoolId).order('created_at',{ascending:false});return{data:data||[],error}};
export const createSchoolTest=async({schoolId,userId,title,classId,level,term,topics,questionCount,durationMinutes,passMark,instructions,startsAt,closesAt,randomizeQuestions=true,randomizeOptions=false})=>{if(!cloud())return fail('Cloud test services are not configured.');if(!schoolId||!userId||!title?.trim())return fail('Test title and school account are required.');const count=Math.max(1,Number(questionCount)||10);let pool=getQuestionsForLevel(level).filter(q=>!topics?.length||topics.includes(q.topic));if(pool.length<count)pool=getQuestionsForLevel(level);pool=shuffle(pool).slice(0,count);if(!pool.length)return fail('No curriculum questions are available for this class level.');const{data:test,error}=await supabase.from('school_tests').insert({school_id:schoolId,created_by:userId,title:title.trim(),subject:'Mathematics',term:term||null,class_id:classId||null,question_count:pool.length,duration_minutes:Math.max(1,Number(durationMinutes)||30),pass_mark:Math.min(100,Math.max(0,Number(passMark)||50)),instructions:instructions||null,randomize_questions:Boolean(randomizeQuestions),randomize_options:Boolean(randomizeOptions),status:'draft',starts_at:startsAt||null,closes_at:closesAt||null}).select('*').single();if(error)return{ok:false,error};const{data:items,error:itemError}=await supabase.from('school_test_items').insert(pool.map((q,index)=>({test_id:test.id,question_id:q.id,position:index+1,points:1,question_snapshot:publicQuestion(q)}))).select('id,question_id,position,points');if(itemError){await supabase.from('school_tests').delete().eq('id',test.id);return{ok:false,error:itemError}}const{error:keyError}=await supabase.from('school_test_answer_keys').insert((items||[]).map((item,index)=>({item_id:item.id,answer:Number(pool[index].answer)})));if(keyError){await supabase.from('school_tests').delete().eq('id',test.id);return{ok:false,error:keyError}}return{ok:true,test,questions:pool}};
export const publishSchoolTest=async testId=>{if(!cloud())return fail('Cloud test services are not configured.');const{data,error}=await supabase.from('school_tests').update({status:'published'}).eq('id',testId).select('*').single();return{ok:!error,data,error}};
export const closeSchoolTest=async testId=>{if(!cloud())return fail('Cloud test services are not configured.');const{data,error}=await supabase.from('school_tests').update({status:'closed'}).eq('id',testId).select('*').single();return{ok:!error,data,error}};
export const getTestItems=async testId=>{if(!cloud()||!testId)return{data:[],error:null};const{data,error}=await supabase.from('school_test_items').select('id,test_id,question_id,position,points,question_snapshot').eq('test_id',testId).order('position');return{data:data||[],error}};
export const createAssignments=async({testId,studentIds})=>{if(!cloud()||!testId)return fail('Test is required.');const ids=[...new Set((studentIds||[]).filter(Boolean))];if(!ids.length)return fail('Select at least one student.');const{data,error}=await supabase.from('school_test_assignments').upsert(ids.map(student_id=>({test_id:testId,student_id,status:'assigned'})),{onConflict:'test_id,student_id'}).select('*');return{ok:!error,data:data||[],error}};
export const assignTestToClass=async({testId,schoolId,classId})=>{if(!cloud())return fail('Cloud test services are not configured.');const{data,error}=await supabase.from('school_enrollments').select('student_id').eq('school_id',schoolId).eq('class_id',classId).eq('status','active');if(error)return{ok:false,error};return createAssignments({testId,studentIds:(data||[]).map(x=>x.student_id)})};
// Student path intentionally avoids selecting school_classes. That relation is school-staff protected and is not needed to load a student's assigned tests. This prevents a student request from invoking staff-only RLS helpers.
export const getStudentAssignments=async studentId=>{if(!cloud()||!studentId)return{data:[],error:null};const{data,error}=await supabase.from('school_test_assignments').select('*,school_tests(title,subject,term,question_count,duration_minutes,pass_mark,instructions,starts_at,closes_at,status,randomize_questions,randomize_options)').eq('student_id',studentId).order('assigned_at',{ascending:false});return{data:data||[],error}};
export const startTest=async assignmentId=>{if(!cloud())return fail('Cloud test services are not configured.');const{data,error}=await supabase.rpc('start_school_test',{p_assignment_id:assignmentId});return{ok:!error,data,error}};
export const submitTestAttempt=async({assignmentId,answers})=>{if(!cloud())return fail('Cloud test services are not configured.');const{data,error}=await supabase.rpc('submit_school_test',{p_assignment_id:assignmentId,p_answers:answers||{}});if(error)return{ok:false,error};return{ok:true,...(data||{})}};
export const getSchoolTestResults=async testId=>{if(!cloud()||!testId)return{data:[],error:null};const{data,error}=await supabase.from('school_test_assignments').select('id,status,student_id,submitted_at,profiles:student_id(full_name,class_level),school_test_attempts(score,percentage,passed,submitted_at)').eq('test_id',testId).order('submitted_at',{ascending:false});return{data:data||[],error}};
export const gradeLabel=p=>p>=75?'A':p>=65?'B':p>=55?'C':p>=45?'D':p>=40?'E':'F';
export const getTopicsForLevel=level=>[...new Set(getQuestionsForLevel(level).map(q=>q.topic).filter(Boolean))].slice(0,60);
