import React,{useEffect,useMemo,useState}from'react';
import{createSchoolAccount,getMySchools,getSchoolOverview,createSchoolClasses}from'./schoolService';
const SECTIONS=[['PRIMARY','Primary','P1–P6'],['JSS','Junior Secondary','JSS1–JSS3'],['SSS','Senior Secondary','SSS1–SSS3']];
const LEVELS={PRIMARY:['P1','P2','P3','P4','P5','P6'],JSS:['JSS1','JSS2','JSS3'],SSS:['SSS1','SSS2','SSS3']};
export default function SchoolPortal({userId,onBack}){const[schoolId,setSchoolId]=useState(''),[school,setSchool]=useState(null),[classes,setClasses]=useState([]),[enabled,setEnabled]=useState([]),[name,setName]=useState(''),[code,setCode]=useState(''),[className,setClassName]=useState(''),[classLevel,setClassLevel]=useState('JSS1'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async id=>{const r=await getSchoolOverview(id);if(r.ok){setSchool(r.school);setClasses(r.classes||[]);setEnabled(r.school?.enabled_sections||[])}else setMessage(r.error?.message||'Unable to load school.')};
 useEffect(()=>{(async()=>{if(!userId)return;const r=await getMySchools(userId);if(r.data?.[0]?.id){setSchoolId(r.data[0].id);load(r.data[0].id)}})()},[userId]);
 const create=async e=>{e.preventDefault();setBusy(true);const r=await createSchoolAccount({schoolName:name,schoolCode:code,sections:enabled,adminUserId:userId});setBusy(false);if(!r.ok){setMessage(r.error?.message||'Unable to create school.');return}setSchoolId(r.school.id);setSchool(r.school);setMessage('School account created successfully.');load(r.school.id)};
 const addClass=async()=>{if(!className.trim())return;setBusy(true);const r=await createSchoolClasses(schoolId,[className.trim()]);setBusy(false);setMessage(r.ok?'Class added.':r.error?.message||'Unable to add class.');if(r.ok){setClassName('');load(schoolId)}};
 const sectionLevels=useMemo(()=>enabled.flatMap(s=>LEVELS[s]||[]),[enabled]);
 if(!schoolId)return <main className="dashboard school-page"><div className="dashhead"><div><p className="step">🏫 MATHBRIDGE SCHOOL</p><h2>Register your school</h2><p className="leveltext">One school account can manage one or more sections.</p></div><button className="secondary" onClick={onBack}>← Back</button></div><form className="account-card" onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} placeholder="School name" required/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="School code e.g. ABC001" required/><h3>Sections offered</h3><div className="section-grid">{SECTIONS.map(([id,label,levels])=><button type="button" key={id} className={enabled.includes(id)?'selected-answer':''} onClick={()=>setEnabled(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}><b>{label}</b><small>{levels}</small></button>)}</div>{message&&<div className="recommend"><b>{message}</b></div>}<button className="primary full" disabled={busy||!enabled.length}>{busy?'Creating…':'Create School Account →'}</button></form></main>;
 return <main className="dashboard school-page"><div className="dashhead"><div><p className="step">🏫 SCHOOL ADMINISTRATION</p><h2>{school?.name}</h2><p className="leveltext">School code: {school?.school_code}</p></div><button className="secondary" onClick={onBack}>← Back</button></div><div className="stats"><div><small>Subscription seats</small><b>{school?.seat_limit||0}</b></div><div><small>Active students</small><b>{school?.active_students||0}</b></div><div><small>Available seats</small><b>{Math.max(0,(school?.seat_limit||0)-(school?.active_students||0))}</b></div></div><div className="report"><h3>Enabled sections</h3><div className="tags">{SECTIONS.filter(([id])=>enabled.includes(id)).map(([id,label,levels])=><span key={id}>✓ {label} · {levels}</span>)}</div></div><div className="report"><h3>Classes & streams</h3><div className="namebox"><select value={classLevel} onChange={e=>setClassLevel(e.target.value)}>{sectionLevels.map(x=><option key={x}>{x}</option>)}</select><input value={className} onChange={e=>setClassName(e.target.value)} placeholder="Class/stream e.g. JSS1A"/><button type="button" className="primary" onClick={addClass} disabled={busy||!className.trim()}>Add Class</button></div>{classes.map(c=><div key={c.id} className="topic-results"><span>{c.class_name}</span><b>{c.section||'School class'}</b></div>)}</div><div className="report"><h3>Students & Test Centre</h3><p>The school workspace is connected to the production data model. Student enrolment, teacher assignment, timed tests and downloadable results will be connected next.</p></div>{message&&<div className="recommend"><b>{message}</b></div>}</main>}
