import React,{useEffect,useMemo,useState}from'react';
import{createSchool,getSchoolOverview,createSchoolClass,removeSchoolStudent}from'./schoolService';

const SECTIONS=[['primary','Primary','P1–P6'],['jss','Junior Secondary','JSS1–JSS3'],['sss','Senior Secondary','SSS1–SSS3']];
const LEVELS={primary:['P1','P2','P3','P4','P5','P6'],jss:['JSS1','JSS2','JSS3'],sss:['SSS1','SSS2','SSS3']};

export default function SchoolPortal({userId,onBack}){
 const[schoolId,setSchoolId]=useState('');const[school,setSchool]=useState(null);const[sections,setSections]=useState([]);const[name,setName]=useState('');const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[className,setClassName]=useState('');const[classLevel,setClassLevel]=useState('JSS1');
 const load=async id=>{const r=await getSchoolOverview(id);if(r.ok){setSchool(r.school);setSections(r.classes||[]);setMessage('')}};
 useEffect(()=>{if(schoolId)load(schoolId)},[schoolId]);
 const create=async e=>{e.preventDefault();setBusy(true);setMessage('');try{const r=await createSchool({name:name.trim(),schoolCode:code.trim().toUpperCase(),userId,sections});if(!r.ok)throw new Error(r.error?.message||'Unable to create school.');setSchoolId(r.school.id);setMessage('School account created successfully.')}catch(e){setMessage(e.message)}finally{setBusy(false)}};
 const addClass=async()=>{if(!schoolId||!className.trim())return;setBusy(true);const r=await createSchoolClass({schoolId,className:className.trim(),levelCode:classLevel});setMessage(r.ok?'Class added.':r.error?.message||'Unable to add class.');if(r.ok){setClassName('');await load(schoolId)}setBusy(false)};
 const selectedSections=useMemo(()=>SECTIONS.filter(([id])=>sections.includes(id)),[sections]);
 if(!schoolId)return <main className="dashboard school-page"><div className="dashhead"><div><p className="step">🏫 MATHBRIDGE SCHOOL</p><h2>Register your school</h2><p className="leveltext">One school account can manage Primary, Junior Secondary and Senior Secondary sections.</p></div><button className="secondary" onClick={onBack}>← Back</button></div><form className="account-card" onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} placeholder="School name" required/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="School code e.g. ABC001" required/><h3>School sections</h3><div className="section-grid">{SECTIONS.map(([id,label,levels])=><button type="button" key={id} className={sections.includes(id)?'selected-answer':''} onClick={()=>setSections(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}><b>{label}</b><small>{levels}</small></button>)}</div>{message&&<div className="recommend"><b>{message}</b></div>}<button className="primary full" disabled={busy||!sections.length}>{busy?'Creating…':'Create School Account →'}</button></form></main>;
 return <main className="dashboard school-page"><div className="dashhead"><div><p className="step">🏫 SCHOOL ADMINISTRATION</p><h2>{school?.name||'School Dashboard'}</h2><p className="leveltext">School code: {school?.school_code}</p></div><button className="secondary" onClick={onBack}>← Back</button></div><div className="stats"><div><small>Seats</small><b>{school?.seat_limit||0}</b></div><div><small>Active students</small><b>{school?.active_students||0}</b></div><div><small>Available seats</small><b>{Math.max(0,(school?.seat_limit||0)-(school?.active_students||0))}</b></div></div><div className="report"><h3>Enabled sections</h3><div className="tags">{selectedSections.map(([id,label,levels])=><span key={id}>✓ {label} · {levels}</span>)}</div></div><div className="report"><h3>Classes</h3><div className="namebox"><select value={classLevel} onChange={e=>setClassLevel(e.target.value)}>{selectedSections.flatMap(([id])=>LEVELS[id]).map(x=><option key={x}>{x}</option>)}</select><input value={className} onChange={e=>setClassName(e.target.value)} placeholder="Stream name e.g. JSS1A"/><button className="primary" onClick={addClass} disabled={busy||!className.trim()}>Add Class</button></div>{sections.length?sections.map(s=><div key={s.id} className="topic-results"><span>{s.class_name}</span><b>{s.level_code}</b></div>):<p>No classes created yet.</p>}</div><div className="report"><h3>Students & Tests</h3><p>Student enrolment, teacher assignment, school tests, timed assessments and downloadable class results are being connected to this school workspace.</p><button className="primary" onClick={()=>setMessage('The Test Centre will be enabled from the next school module release.')}>Open Test Centre →</button></div>{message&&<div className="recommend"><b>{message}</b></div>}</main>;
}
