import React,{useEffect,useMemo,useState}from'react';
import{createSchoolAccount,getMySchools,getSchoolOverview,getSchoolRoster,createSchoolClasses,removeStudentFromSchool,getMyRole}from'./schoolService';
import SchoolTestCentre from'./SchoolTestCentre';
import StudentTestCentre from'./StudentTestCentre';
const SECTIONS=[['PRIMARY','Primary','P1–P6'],['JSS','Junior Secondary','JSS1–JSS3'],['SSS','Senior Secondary','SSS1–SSS3']];
const LEVELS={PRIMARY:['P1','P2','P3','P4','P5','P6'],JSS:['JSS1','JSS2','JSS3'],SSS:['SSS1','SSS2','SSS3']};
export default function SchoolPortal({userId,onBack}){const[schoolId,setSchoolId]=useState(''),[school,setSchool]=useState(null),[classes,setClasses]=useState([]),[roster,setRoster]=useState([]),[enabled,setEnabled]=useState([]),[role,setRole]=useState(null),[name,setName]=useState(''),[code,setCode]=useState(''),[className,setClassName]=useState(''),[classLevel,setClassLevel]=useState('JSS1'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async id=>{const r=await getSchoolOverview(id);if(r.ok){setSchool(r.school);setClasses(r.classes||[]);setEnabled(r.school?.enabled_sections||[]);const rr=await getSchoolRoster(id);if(rr.ok)setRoster(rr.data||[])}else setMessage(r.error?.message||'Unable to load school.')};
 useEffect(()=>{(async()=>{if(!userId){setMessage('Please sign in first.');return}const pr=await getMyRole(userId);if(pr.error){setMessage(pr.error.message||'Unable to verify account role.');return}setRole(pr.role);if(pr.role!=='school_admin')return;const r=await getMySchools(userId);if(r.error){setMessage(r.error.message||'Unable to load school access.');return}if(r.data?.[0]?.id){setSchoolId(r.data[0].id);load(r.data[0].id)}})()},[userId]);
 const create=async e=>{e.preventDefault();setBusy(true);const r=await createSchoolAccount({schoolName:name,schoolCode:code,sections:enabled,adminUserId:userId});setBusy(false);if(!r.ok){setMessage(r.error?.message||'Unable to create school.');return}setSchoolId(r.school.id);setSchool(r.school);setMessage('School account created successfully.');load(r.school.id)};
 const addClass=async()=>{if(!className.trim()||!classLevel)return;setBusy(true);const r=await createSchoolClasses(schoolId,{className,classLevel,stream:null});setBusy(false);setMessage(r.ok?'Class added.':r.error?.message||'Unable to add class.');if(r.ok){setClassName('');load(schoolId)}};
 const remove=async enrollmentId=>{if(!window.confirm('Remove this student from the school? Their MathBridge account and learning history will be preserved.'))return;setBusy(true);const r=await removeStudentFromSchool(enrollmentId);setBusy(false);setMessage(r.ok?'Student removed from active school enrolment.':r.error?.message||'Unable to remove student.');if(r.ok)load(schoolId)};
 const sectionLevels=useMemo(()=>enabled.flatMap(s=>LEVELS[s]||[]),[enabled]);
 if(role==='student')return <StudentTestCentre studentId={userId} onBack={onBack}/>;
 if(role&&role!=='school_admin')return <main className="dashboard school-page"><div className="dashhead"><div><p className="step">🏫 SCHOOL ADMINISTRATION</p><h2>School access restricted</h2><p className="leveltext">This area is available only to verified MathBridge school administrators.</p></div><button className="secondary" onClick={onBack}>← Back</button></div><div className="account-card"><p>Your current account role is <b>{role.replace('_',' ')}</b>. A student, parent or teacher account cannot create or manage a school subscription.</p><button className="primary" onClick={onBack}>Return to MathBridge</button></div></main>;
 if(!schoolId)return <main className="dashboard school-page"><div className="dashhead"><div><p className="step">🏫 MATHBRIDGE SCHOOL</p><h2>Register your school</h2><p className="leveltext">One school account can manage one or more sections.</p></div><button className="secondary" onClick={onBack}>← Back</button></div><form className="account-card" onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} placeholder="School name" required/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="School code e.g. ABC001" required/><h3>Sections offered</h3><div className="section-grid">{SECTIONS.map(([id,label,levels])=><button type="button" key={id} className={enabled.includes(id)?'selected-answer':''} onClick={()=>setEnabled(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}><b>{label}</b><small>{levels}</small></button>)}</div>{message&&<div className="recommend"><b>{message}</b></div>}<button className="primary full" disabled={busy||!enabled.length}>{busy?'Creating…':'Create School Account →'}</button></form></main>;
 return <main className="dashboard school-page"><div className="dashhead"><div><p className="step">🏫 SCHOOL ADMINISTRATION</p><h2>{school?.name}</h2><p className="leveltext">School code: {school?.school_code}</p></div><button className="secondary" onClick={onBack}>← Back</button></div><div className="stats"><div><small>Subscription seats</small><b>{school?.seat_limit||0}</b></div><div><small>Active students</small><b>{school?.active_students||0}</b></div><div><small>Available seats</small><b>{school?.available_seats??Math.max(0,(school?.seat_limit||0)-(school?.active_students||0))}</b></div></div><div className="report"><h3>Enabled sections</h3><div className="tags">{SECTIONS.filter(([id])=>enabled.includes(id)).map(([id,label,levels])=><span key={id}>✓ {label} · {levels}</span>)}</div></div><div className="report"><h3>Classes & streams</h3><div className="namebox"><select value={classLevel} onChange={e=>setClassLevel(e.target.value)}>{sectionLevels.map(x=><option key={x}>{x}</option>)}</select><input value={className} onChange={e=>setClassName(e.target.value)} placeholder="Class/stream e.g. JSS1A"/><button type="button" className="primary" onClick={addClass} disabled={busy||!className.trim()}>Add Class</button></div>{classes.map(c=><div key={c.id} className="topic-results"><span>{c.class_name}</span><b>{c.class_level||c.section||'School class'}</b></div>)}</div><div className="report"><h3>Students</h3>{roster.length?<div>{roster.map(r=><div key={r.id} className="topic-results"><span>{r.profiles?.full_name||'Student'}<small>{r.school_classes?.class_name||'Unassigned'} · {r.profiles?.class_level||''}</small></span><b>{r.status==='active'?'Active':'Inactive'} <button type="button" className="secondary" onClick={()=>remove(r.id)} disabled={busy||r.status!=='active'}>Remove</button></b></div>)}</div>:<p>No students are enrolled yet. Student invite/enrolment is the next connection point.</p>}</div><SchoolTestCentre schoolId={schoolId} userId={userId} classes={classes} roster={roster}/>{message&&<div className="recommend"><b>{message}</b></div>}</main>}
