import React,{useEffect,useMemo,useState}from'react';
import{getStudentAssignments,getTestItems,startTest,submitTestAttempt}from'./schoolTests';
const fmt=s=>{const m=Math.floor(s/60),sec=s%60;return`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};
export default function StudentTestCentre({studentId,onBack}){const[assignments,setAssignments]=useState([]),[active,setActive]=useState(null),[items,setItems]=useState([]),[answers,setAnswers]=useState({}),[index,setIndex]=useState(0),[remaining,setRemaining]=useState(0),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[message,setMessage]=useState('');
 const load=async()=>{const r=await getStudentAssignments(studentId);if(r.error)setMessage(r.error.message||'Unable to load assigned tests.');else setAssignments(r.data||[])};
 useEffect(()=>{if(studentId)load()},[studentId]);
 const finish=async timed=>{if(!active||busy)return;setBusy(true);const r=await submitTestAttempt({assignmentId:active.id,answers});setBusy(false);if(!r.ok){setMessage(r.error?.message||'Unable to submit test.');return}setResult({...r,timed});setActive(null);load()};
 useEffect(()=>{if(!active||result)return;const timer=setInterval(()=>setRemaining(x=>{if(x<=1){clearInterval(timer);finish(true);return 0}return x-1}),1000);return()=>clearInterval(timer)},[active,result]);
 const begin=async a=>{setMessage('');if(a.status==='submitted')return;setBusy(true);let started=a;if(a.status==='assigned'){const r=await startTest(a.id);if(!r.ok){setBusy(false);setMessage(r.error?.message||'Unable to start test.');return}started={...a,...r.data}}const r=await getTestItems(a.test_id);setBusy(false);if(r.error||!r.data?.length){setMessage(r.error?.message||'This test has no questions.');return}const test=started.school_tests||a.school_tests||{};const shuffled=test.randomize_questions?[...r.data].sort(()=>Math.random()-.5):r.data;const duration=Math.max(60,Number(test.duration_minutes||30)*60);const startedAt=started.started_at?new Date(started.started_at).getTime():Date.now();const elapsed=Math.max(0,Math.floor((Date.now()-startedAt)/1000));const left=Math.max(0,duration-elapsed);setActive({...started,school_tests:test});setItems(shuffled);setAnswers({});setIndex(0);setRemaining(left);if(left<=0)window.setTimeout(()=>finish(true),0)};
 const q=items[index];const answered=Object.keys(answers).length;const pct=useMemo(()=>items.length?Math.round(answered/items.length*100):0,[answered,items.length]);
 if(result)return <main className="dashboard"><div className="dashhead"><div><p className="step">TEST COMPLETE</p><h2>{result.percentage}%</h2><p className="leveltext">{result.passed?'🎉 Passed':'Keep practising — you can improve this result.'}{result.timed?' · Submitted automatically when time ended.':''}</p></div><button className="secondary" onClick={()=>{setResult(null);onBack?.()}}>← Back</button></div><div className="report"><h3>Assessment result</h3><p>Score: <b>{result.score}</b></p><p>Percentage: <b>{result.percentage}%</b></p><p>Status: <b>{result.passed?'PASS':'NOT YET PASSED'}</b></p></div></main>;
 if(active&&q)return <main className="quiz"><div className="dashhead"><div><p className="step">{active.school_tests?.title||'School Test'}</p><p className="leveltext">Question {index+1} of {items.length} · {answered}/{items.length} answered</p></div><div className="badge">{fmt(remaining)}</div></div><div className="progress"><span style={{width:`${pct}%`}}/></div><div className="topic-label">{q.question_snapshot?.topic||'Mathematics'}</div><h2>{q.question_snapshot?.q||'Question unavailable'}</h2><div className="answers">{(q.question_snapshot?.options||[]).map((x,n)=><button type="button" key={`${q.id}-${n}`} className={answers[q.id]===n?'selected-answer':''} onClick={()=>setAnswers(a=>({...a,[q.id]:n}))}>{x}<span>{answers[q.id]===n?'✓':'→'}</span></button>)}</div><div className="question-nav"><button className="secondary" type="button" disabled={index===0} onClick={()=>setIndex(index-1)}>← Back</button>{index<items.length-1?<button className="primary" type="button" onClick={()=>setIndex(index+1)}>Next →</button>:<button className="primary" type="button" disabled={busy} onClick={()=>finish(false)}>{busy?'Submitting…':'Submit Test'}</button>}</div><p className="encourage">Your selected answer is highlighted. You can change it before submitting.</p></main>;
 return <main className="dashboard"><div className="dashhead"><div><p className="step">📝 SCHOOL TEST CENTRE</p><h2>My Tests</h2><p className="leveltext">Complete assessments assigned to you by your school.</p></div><button className="secondary" onClick={onBack}>← Back</button></div>{message&&<div className="recommend"><b>{message}</b></div>}{assignments.length?assignments.map(a=><div className="report" key={a.id}><div className="topic-results"><span><b>{a.school_tests?.title||'School Test'}</b><small>{a.school_tests?.school_classes?.class_name||''} · {a.school_tests?.term||''} · {a.school_tests?.question_count||0} questions · {a.school_tests?.duration_minutes||0} min</small></span><b>{a.status==='submitted'?'Submitted':a.status==='started'?'Continue':'Assigned'}</b></div>{a.school_tests?.instructions&&<p>{a.school_tests.instructions}</p>}{a.status!=='submitted'&&<button className="primary" onClick={()=>begin(a)} disabled={busy}>{a.status==='started'?'Continue Test':'Start Test →'}</button>}</div>):<div className="account-card"><h3>No tests assigned</h3><p>Your school has not assigned a test to your account yet.</p></div>}</main>}
