import React,{useState}from'react';
import{levelOptions}from'./data/curriculum';
import{getSchoolJoinOptions,joinSchoolByCode}from'./cloudProgress';

export default function StudentSchoolJoin({userId,classLevel,setClassLevel,busy,setBusy,message,setMessage,onBack,onContinue,submitClass}){
 const[mode,setMode]=useState('individual'),[schoolCode,setSchoolCode]=useState(''),[school,setSchool]=useState(null),[selectedClass,setSelectedClass]=useState('');
 const lookup=async()=>{if(!schoolCode.trim())return;setBusy(true);setMessage('Finding your school…');try{const r=await getSchoolJoinOptions(schoolCode);if(r.error)throw r.error;setSchool(r.data);setSelectedClass(r.data?.classes?.[0]?.id||'');setMessage(r.data?.school_name?'School found. Select your class.':'No classes are available yet.')}catch(e){setSchool(null);setMessage(e?.message||'School code not found.')}finally{setBusy(false)}};
 const join=async()=>{if(!selectedClass)return;setBusy(true);setMessage('Joining your school…');try{const r=await joinSchoolByCode(schoolCode,selectedClass);if(r.error)throw r.error;setMessage('School enrolment complete. Your personal learning progress remains yours.');setTimeout(()=>onContinue?.(),500)}catch(e){setMessage(e?.message||'Unable to join this school.')}finally{setBusy(false)}};
 return <main className="auth-page"><section className="auth-shell"><div className="auth-brand-panel"><button type="button" className="auth-logo" onClick={onBack}>Math<span>Bridge</span></button><div className="auth-brand-content"><span className="auth-eyebrow">🇳🇬 NIGERIAN CURRICULUM MATHS</span><h1>Let’s set up<br/><span>your learning.</span></h1><p>Your account is ready. Tell MathBridge how you are learning so we can place you on the correct curriculum journey.</p><div className="auth-benefits"><div><span>✓</span><div><b>Individual learning</b><small>Your own progress and mastery history.</small></div></div><div><span>✓</span><div><b>School learning</b><small>Join your school's class and assigned tests.</small></div></div></div></div><p className="auth-footer">You can change your class later.</p></div><div className="auth-form-panel"><div className="auth-heading"><span className="auth-icon">🎓</span><p className="auth-kicker">ONE-TIME SETUP</p><h2>Choose your learning path</h2><p>Your first term automatically begins at Week 1.</p></div><div className="setup-choice"><button type="button" className={mode==='individual'?'active':''} onClick={()=>setMode('individual')}>🎓 Individual</button><button type="button" className={mode==='school'?'active':''} onClick={()=>setMode('school')}>🏫 School</button></div>{mode==='individual'?<form className="auth-form" onSubmit={submitClass}><label><span>School level & class</span><select value={classLevel} onChange={e=>setClassLevel(e.target.value)}>{levelOptions.map(x=><option key={x.value} value={x.value}>{x.group} — {x.label}</option>)}</select><small>This determines your curriculum, weekly topics and question bank.</small></label><button className="primary auth-submit" type="submit" disabled={busy}>{busy?'Saving…':'Save Class & Start Maths →'}</button></form>:<div className="auth-form"><label><span>School code</span><input value={schoolCode} onChange={e=>setSchoolCode(e.target.value.toUpperCase())} placeholder="e.g. ABC001"/></label><button type="button" className="secondary auth-submit" onClick={lookup} disabled={busy||!schoolCode.trim()}>{busy?'Checking…':'Find My School'}</button>{school&&<label><span>Your school class</span><select value={selectedClass} onChange={e=>setSelectedClass(e.target.value)}>{(school.classes||[]).map(x=><option key={x.id} value={x.id}>{x.class_name} — {x.class_level}</option>)}</select></label>}{school&&<button type="button" className="primary auth-submit" onClick={join} disabled={busy||!selectedClass}>{busy?'Joining…':'Join School & Start Maths →'}</button>}</div>}{message&&<div className="auth-message" role="status"><b>{message}</b></div>}<p className="auth-footer">You will begin at First Term • Week 1.</p></div></section></main>;
}