import React,{useEffect,useMemo,useState}from'react';
import{jss1Weekly}from'./data/jss1Weekly';
import{selectFreshQuestions}from'./questionSelection';
import{getCloudSeenQuestionIds,recordQuestionExposure,recordQuestionAnswer}from'./questionHistory';
import{completeWeek,completeTermExam}from'./progression';

const normalize=s=>String(s||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').trim();
const matchesTopic=(questionTopic,target)=>{const q=normalize(questionTopic),t=normalize(target);return q===t||q.includes(t)||t.includes(q)||q.split(' ').filter(w=>w.length>4).some(w=>t.includes(w));};
const weekPool=(allQuestions,term,week)=>{const weeks=jss1Weekly[term]||[];const current=weeks.find(w=>w.week===week);if(!current)return allQuestions;const targets=current.topics||[];const pool=allQuestions.filter(q=>targets.some(t=>matchesTopic(q.topic,t)));return pool.length>=6?pool:allQuestions;};
const termPool=(allQuestions,term)=>{const weeks=jss1Weekly[term]||[];const targets=[...new Set(weeks.flatMap(w=>w.topics||[]))];const pool=allQuestions.filter(q=>targets.some(t=>matchesTopic(q.topic,t)));return pool.length>=20?pool:allQuestions;};

export default function WeeklyAssessment({mode='weekly',level='JSS1',term='T1',week=1,questions=[],progress,onDone,onBack}){
 const isExam=mode==='exam';const weeks=jss1Weekly[term]||[];const total=isExam?20:10;
 const [items,setItems]=useState([]),[index,setIndex]=useState(0),[answers,setAnswers]=useState({}),[result,setResult]=useState(null),[busy,setBusy]=useState(true);
 const pool=useMemo(()=>isExam?termPool(questions,term):weekPool(questions,term,week),[questions,term,week,isExam]);
 useEffect(()=>{let alive=true;(async()=>{setBusy(true);const activityTypes=isExam?['exam','weekly','diagnostic','practice','mastery','test']:['weekly','diagnostic','practice','mastery','test'];const historyLists=await Promise.all(activityTypes.map(a=>getCloudSeenQuestionIds(progress?.studentId||null,level,a).catch(()=>[])));const history=[...new Set(historyLists.flat().map(String))];const selected=selectFreshQuestions({userId:progress?.studentId||'local-user',questions:pool,count:total,byTopic:true,seenIds:history});if(alive){setItems(selected);setIndex(0);setAnswers({});setResult(null);setBusy(false)}})();return()=>{alive=false}},[term,week,level,isExam,pool,progress?.studentId,total]);
 useEffect(()=>{if(!items.length)return;items.forEach(q=>{recordQuestionExposure({studentId:progress?.studentId||'local-user',questionId:q.id,level,topic:q.topic,activityType:isExam?'exam':'weekly'}).catch(()=>{})})},[items,isExam,level,progress?.studentId]);
 const selected=items[index];const chosen=selected?answers[selected.id]:undefined;
 const answer=n=>{if(selected)setAnswers(a=>({...a,[selected.id]:n}))};
 const submit=async()=>{if(chosen===undefined||busy)return;if(index<items.length-1){setIndex(index+1);return}setBusy(true);let correct=0;for(const q of items){const ok=answers[q.id]===q.answer;if(ok)correct++;await recordQuestionAnswer({studentId:progress?.studentId||'local-user',questionId:q.id,activityType:isExam?'exam':'weekly',correct:ok,level}).catch(()=>{})}const score=items.length?Math.round(correct/items.length*100):0;const passed=score>=80;let nextProgress=progress;if(isExam)nextProgress=completeTermExam(progress,term,score,80);else if(passed)nextProgress=completeWeek(progress,term,week);setResult({score,passed,correct,total:items.length,nextProgress});setBusy(false)};
 if(busy)return <main className="quiz weekly-assessment"><div className="pill">📚 Preparing your challenge</div><h2>Building a fresh {isExam?'term exam':'weekly test'} for you…</h2><p className="lead">MathBridge is checking your question history so we do not keep showing the same questions.</p></main>;
 if(!items.length)return <main className="quiz weekly-assessment"><div className="pill">⚠️ Question bank</div><h2>We could not prepare this assessment.</h2><p className="lead">Please try again. Your learning progress has not been changed.</p><button className="secondary" onClick={onBack}>← Back to My Progress</button></main>;
 if(result){const termName=term==='T1'?'First':term==='T2'?'Second':'Third';return <main className="result weekly-assessment"><div className="badge">{result.passed?'🏆':'💪'}</div><p className="step">{isExam?'END-OF-'+termName.toUpperCase()+'-TERM EXAM':'WEEK '+week+' TEST RESULT'}</p><h2>{result.passed?'Excellent work!':'Keep going — you have not unlocked the next stage yet.'}</h2><div className="score"><strong>{result.score}%</strong><span>{result.correct}/{result.total} correct</span></div><div className="report"><h3>{isExam?(result.passed?'You passed the '+termName+' Term Final Exam.':'You need 80% to move to the next term.'):(result.passed?'Week '+week+' is mastered.':'Week '+week+' remains in progress.')}</h3><p>{isExam?(result.passed?(result.nextProgress.term!==term?'Welcome to '+(result.nextProgress.term==='T2'?'Second':'Third')+' Term. Your new term starts at Week 1.':'You have completed the full JSS1 term sequence.'):'Try the final exam again after reviewing the term. A fresh question set will be selected.'):(result.passed?(week<weeks.length?'Week '+(week+1)+' is now unlocked.':'All instructional weeks are complete. Your Term Final Exam is now unlocked.'):'Review the week\'s topics and try again. Your next attempt will use different questions.')}</p></div><button className="primary" onClick={()=>onDone?.(result.nextProgress,result)}>{result.passed?(isExam?'Continue Learning →':week<weeks.length?'Start Next Week →':'Start Term Final Exam →'):'Try Again With Fresh Questions →'}</button></main>}
 const termName=term==='T1'?'First':term==='T2'?'Second':'Third';return <main className="quiz weekly-assessment"><div className="progress"><span style={{width:((index+1)/items.length*100)+'%'}}/></div><p className="step">{isExam?'JSS1 • '+termName.toUpperCase()+' TERM FINAL EXAM':'JSS1 • '+termName.toUpperCase()+' TERM • WEEK '+week}</p><div className="topic-label">{isExam?'FINAL TERM EXAM':'WEEKLY MASTERY TEST'}</div><h2>{selected.q}</h2><div className="answers">{selected.options.map((x,n)=><button type="button" className={chosen===n?'selected-answer':''} key={selected.id+'-'+n} onClick={()=>answer(n)}>{x}<span>{chosen===n?'✓':'→'}</span></button>)}</div><div className="question-nav"><button className="secondary" onClick={()=>index>0&&setIndex(index-1)} disabled={index===0}>← Back</button><button className="primary" onClick={submit} disabled={chosen===undefined}>{index===items.length-1?'Submit Test':'Next →'}</button></div><p className="encourage">Fresh questions are selected from your class and term history.</p></main>;
}